### ISSUE TITLE
Weird ZoneAwareError: (SystemJS) Unexpected token < SyntaxError

### ISSUE THREAD

**Issue by senglory** [kutyel/linq.ts#69] opened 2017-05-23 10:21 UTC
My code in TS:

```typescript
import { List } from 'linqts';

let qq = new List<Dienst>(cust.custDienst);
```

This code gives no errors upon TS compiler run but explodes in my browser.

**Comment by kutyel** [comment] 2017-05-23 10:41
Please check the answers at #12, #16, #41 who had a the same issue and solved it. This is not a bug from the library. 😉

**Comment by senglory** [comment] 2017-05-23 15:57
#12 - don't understand how it corresponds with my issue. Could you please shed some light on it?

#16 - closed by no answers

#41 - I use linqts with the latest version (1/8/2 if I'm not mistaken)


Still have this issue opened...

**Comment by kutyel** [comment] 2017-05-24 06:42
Ok, fair enough. Please share your config of SystemJS and tsconfig etc with steps to reproduce. I am already serving with the library.

1. UMD module (browser)
2. CommonJS module (node)
3. Source code in TypeScript to be compiled manually

There is no `ZoneAwareError` object anywhere in this library, which makes me think that is probably some miss configuration rather than an actual bug in this library.

**Comment by senglory** [comment] 2017-05-24 17:52
[https://1drv.ms/u/s!ArGxIywiws8MgUndQs9bfUH_E6UA](url)

Here's my project on Angular 2.

**Comment by kutyel** [comment] 2017-05-26 07:19
The link is broken 😕

**Comment by abbasmhd** [comment] 2017-05-26 09:54
the url works you just have to copy and past it

**Comment by kutyel** [comment] 2017-05-26 09:57
Ok, will have a look when I find the time 😉

**Comment by kutyel** [comment] 2017-09-18 12:27
Hi @senglory is this still an issue? Did you find a workaround? I know of many people in the A2/4 community using this library without problems, would like to close this....

**Comment by kutyel** [comment] 2017-10-16 06:47
This should be closed, added and explicit export for Angular 2 project which specifically points you to the TS code to be compiled on usage.

**Closed by kutyel** 2017-10-16 06:47 UTC
Labels: discussion, enhancement, Hacktoberfest, help wanted, question
