### ISSUE TITLE
How to import linq.ts into module

### ISSUE THREAD

**Issue by NickAb** [kutyel/linq.ts#12] opened 2016-05-18 03:49 UTC
I have my angular 1.5 typescript app organised in several files: app.ts, controller.ts, ientity.ts etc. All files re wrapped in `module MyApp {}`. In tsconfig I have `outFile` option set so that everything compiles into a single app.js file.

How do I use linq.ts in such project? If I try to `import {List} from "linqts"` at the top of any of my *.ts files outside `module MyApp` then compilation breaks because of compiler not being able to find types defined in same module but another file (for example interfaces declared in ientity.ts are no longer valid in controller.ts).

But if I put import declaration inside `module MyApp {}` then I get following compiler error:
`TS1147	Import declarations in a namespace cannot reference a module.`

What is correct why to use this library in multi-file single module project setup?
Am not sure if it might affect, but I use typings to reference angular, underscore, etc.

**Comment by kutyel** [comment] 2016-05-18 20:50
I think that this is not an issue of the library itself, but on the architecture approach you are trying. From some time ago, external modules or namespaces are **not recommended** in TypeScript. While the common approach is to just export classes or variables in certain files, just as I am doing here. This is the  way Angular 2 works, for example, and other TypeScript big projects. Maybe you can find some inspiration [here](https://www.typescriptlang.org/docs/handbook/modules.html) or at [this](http://stackoverflow.com/questions/30357634/how-do-i-use-namespaces-with-typescript-external-modules) answer in StackOverflow.

I will try what you mean when I have a sec, though, and see if I can provide you with a better solution. Thanks for submitting the issue and for using the library!

**Comment by kutyel** [comment] 2016-05-22 11:28
I think @Kurtz1993 can give you some advise in how to use the library with Angular 1.x. Looking forward to that. 😉

**Comment by Kurtz1993** [comment] 2016-05-22 13:12
Mmm... I think that's because of the use of modules/namespaces. Are you targeting commonjs, amd or system modules?

And the typings issue must be on the typings.d.ts that doesn't have the reference of the linq.d.ts file.

**Comment by Kurtz1993** [comment] 2016-05-22 13:37
Now that I tried to reproduce this error I get it. I think this issue can be part of how the TypeScript compiler was created. I've used to work with projects that used only namespaces, no `import` declarations.

I think that the best approach to follow here is not using namespaces and use CommonJS or AMD modules instead. If you use CommonJS modules, you can use Webpack as your compilation process to output to a single file [Here's a webpack.config.js sample for TS.](https://gist.github.com/Kurtz1993/299b28a08e0a1a587d75)

**Comment by kutyel** [comment] 2016-05-23 05:51
Thanks @Kurtz1993! I will add a webpack and browser sample to the readme file ASAP in order yo close this issue! :+1:

**Closed** 2016-06-05 18:29 UTC
Labels: help wanted, question

**Comment by NickAb** [comment] 2016-06-06 15:36
Thanks

**Comment by kutyel** [comment] 2016-06-06 16:56
@NickAb Your welcome! 😄
