### ISSUE TITLE
Import issue in nodejs ts app

### ISSUE THREAD

**Issue by hozjanmarko** [kutyel/linq.ts#175] opened 2020-10-08 20:11 UTC
```export { default as List } from './list';
^^^^^^

SyntaxError: Unexpected token 'export'```

npm ver:^1.14.3

**Comment by kutyel** [comment] 2020-10-08 21:38
Feel free to open a PR, this has something to do with our build pipeline with microbundle @developit 😭

**Comment by hozjanmarko** [comment] 2020-10-08 22:34
Do you really need microbundle?

**Comment by kutyel** [comment] 2020-10-09 08:18
Maybe not, feel free to propose an alternative that supports both browser and node 😉

**Comment by developit** [comment] 2020-10-09 21:44
This isn't a problem in Microbundle, it's a misconfiguration. Microbundle isn't being run when the module is built, it's just relying on `tsc`. 

You need a package.json like this:

```jsonc
{
  "source": "index.ts", // source code
  "main": "./dist/linq.js", // old node/webpack
  "module": "./dist/linq.mjs", // for bundlers
  "exports": "./dist/linq.mjs", // for node import()
  "scripts": {
    "build": "microbundle"
  }
}
```

**Comment by Rechdan** [comment] 2020-12-30 19:16
Having this problem here:
```
/app/node_modules/linqts/dist/src/index.js:10

export { default as List } from './list';

^^^^^^
```

**Comment by kutyel** [comment] 2020-12-31 09:17
@Rechdan can you please provide steps to reproduce? The rest of the people seem not to have this problem anymore...

**Comment by Rechdan** [comment] 2020-12-31 13:36
@kutyel sure, here is my package.json:
```json
{
	"name": "server",
	"version": "1.0.0",
	"license": "MIT",
	"scripts": {
		"dev": "nodemon --legacy-watch --watch ./src --ext ts,tsx --exec \"npm install && npm run dev-run\"",
		"dev-run": "ts-node --transpile-only --project ./tsconfig.json --require tsconfig-paths/register ./src/index.ts"
	},
	"dependencies": {
		"argon2": "0.27.1",
		"async-lock": "1.2.6",
		"axios": "0.21.1",
		"express": "4.17.1",
		"helmet": "4.3.0",
		"moment": "2.29.1",
		"morgan": "1.10.0",
		"mysql": "2.18.1",
		"node-cache": "5.1.2",
		"ts-node": "9.1.1",
		"tsconfig-paths": "3.9.0",
		"typeorm": "0.2.29",
		"yup": "0.32.8"
	},
	"devDependencies": {
		"@types/async-lock": "1.1.2",
		"@types/express": "4.17.9",
		"@types/morgan": "1.9.2",
		"@types/node": "14.14.16",
		"concurrently": "5.3.0",
		"nodemon": "2.0.6",
		"typescript": "4.1.3"
	}
}
```
And to reproduce is simple, I just run the `dev` command and I get this error.

**Comment by kutyel** [comment] 2021-01-12 09:42
Closed as a duplicate of https://github.com/kutyel/linq.ts/issues/163

**Closed by kutyel** 2021-01-12 09:42 UTC
Labels: Hacktoberfest, bug, help wanted
